// Physical silhouettes are authored separately from gameplay so each small icon remains recognizable.
const tank = {
 radio_1:['a wooden puppet control cross linked by one gold thread to an ivory doll-face relay box','a small bronze handbell hung between two ivory charms with a red cord','a detached horn-rimmed beast throat with a crimson voice sac on an iron mount'],
 radio_2:['three wooden puppet control crosses joined by parallel golden threads','a squat bronze ritual clock with three dangling ivory charm pendulums','a shallow horizontal bone-rimmed war drum with a red hide membrane and two beaters'],
 radio_3:['an open rectangular wooden chest containing three ivory doll heads and violet memory chips','a broad bronze ritual ring around a large blue spirit bead with four ivory charms','a serrated bone beast-king crown with two long horns and a central crimson eye'],
 smoke:['an open wooden launch box holding two small hollow porcelain puppet decoys','a folding screen of three ivory charms with a curved blue refractive barrier','a shed hollow beast shell beside a small red lure sac'],
 wet_storage:['a long closed wooden crystal coffin with thick brass bands and one purple window','an ivory paper seal wrapped around a tightly bound bronze spirit vessel','three blunt bone restraint nails pinning down a dark overlapping scale'],
 maintenance:['three flat violet memory chips in a shallow wooden spare-personality case','two torn ivory charms rejoined by a red stitching cord on a bronze frame','a crimson living repair pouch holding two crossed ivory bone fragments'],
 secondary_mg:['three tiny ivory clockwork puppet bodies holding small violet star emitters','a horizontal bronze hoop carrying six ivory interception charms','a black-feather parasite nest with five silver-edged pointed feathers'],
 secondary_cannon:['a broad triangular violet refracting prism in a low brass cannon cradle','a short bronze focusing barrel with an ivory charm sleeve and a narrow blue lance','a telescoping ivory beast horn extending from a ribbed black-iron socket'],
 secondary_howitzer:['two violet crystal forks around a large purple resonance orb on a squat brass base','three square ivory ground-thunder charms on a low bronze rack with one blue spark','a cracked crimson egg with orange energy inside a low bone-ribbed launcher'],
 secondary_lance:['a very long thin violet crystal needle in a compact brass focusing collar','a long silver exorcism spike wrapped with one ivory charm and red thread','a long coiled crimson tentacle with an ivory piercing claw at its tip'],
 secondary_aa:['a horizontal oval rail carrying two tiny ivory turret puppets and a violet star','an arc of five ivory sky-sealing charms in a bronze frame with a blue feather','a spring-mounted crimson tongue curled around two rigid black feathers'],
 secondary_flame:['a flared brass relief nozzle venting a short contained violet magical flame','a squat bronze ritual furnace surrounded by four ivory fire charms and an orange flame','a detached dark-red breath gland with a bone nozzle and a tiny contained orange flame'],
 coax:['three fine long brass sewing needles threaded with violet enchanted string','three small overlapping exorcism charms held in a miniature red-tied bronze bracket','a small dark organic mouth with three ivory dart teeth projecting forward'],
 stabilizer:['a little ivory puppet seated beside a miniature wooden prediction board','a blue circular spirit eye inside a broad bronze stabilizing ring','a cluster of three amber hunting eyes in a dark armored cheek plate'],
 sloped_shield:['a broad slanted oval violet mirror with an ornate brass rim','three overlapping translucent pale-blue barrier plates backed by ivory charms','a broad mottled gray petrified hide armor slab with red veins'],
 skirts:['three levitating ivory shield plates joined by gold strings around a violet focus','four short ivory talisman banners on a horizontal bronze side rail','a horizontal row of four large ivory bone spikes growing from a dark hide strip'],
 extra_magazine:['three exposed violet crystals linked end to end by dangerous brass connectors','a rectangular open bronze magazine packed tightly with rolled ivory charms','a crimson swollen nutrient gland strapped into a black-iron cage'],
 dozer:['an open square wooden box with a tiny ivory digging puppet and a miniature shovel','two squat bronze ritual footing stakes tied with ivory earth charms','a pair of thick dark clawed digging forelimbs held in a low iron mount'],
 fuel_drum:['a rounded purple magical glass bottle with a brass cork and leather straps','a rectangular bronze prayer-storage box tied with red cord and ivory seals','a plump dark-red dormant beast stomach sac with a black-iron belt'],
 toolbox:['a tiny ivory puppet holding a wide gold thread comb beside a tangled violet spool','a wooden drying rack supporting three hanging ivory charms','an open shallow bone-edged box containing three tiny dark cleaning beetles'],
 signal_flags:['an open cream-colored dance score on a small wooden music stand, abstract dots only','a slanted bamboo divination cylinder containing several plain wooden sticks','a short red cloth banner on a bone pole decorated with two large beast teeth'],
 ornamental_armor:['an open rectangular wooden music box with a brass winding key and a tiny ivory dancing doll','three small bronze wind bells suspended from a horizontal red cord','a separate second pair of sweeping ivory ornamental horns on a dark iron base'],
 parade_lights:['a small brass projection lantern throwing one restrained violet puppet-shaped illusion','a squat red-and-bronze festival offering lantern with a blue spirit flame','a shallow dark tray covered in softly glowing crimson moss clumps'],
 crew_comfort:['a shallow wooden tea tray with two tiny ivory cups and a porcelain teapot','a squat bronze incense censer with a lid and a small curling blue wisp','a thick gray grinding stone bearing two tooth grooves and a red beast cord'],
 spare_tracks:['two unpowered ivory puppet bodies folded into a wooden storage crate','an open square wooden paper box full of neatly stacked blank ivory sheets','a dormant dark beast leg curled inside a thick red organic pouch'],
 emergency_battery:['a second violet crystal core with warning-like abstract binding seals and brass cage','a fan of burning ivory charms on a low bronze propulsion ring','a crimson hunting-catalyst gland with spiky black ribs and two sharp bone tubes'],
 cooling_fins:['a broad comb of violet crystal fins in a low brass heat-release rail','a wide bronze balancing ring encircling two pale-blue spirit beads','three horizontal red blood gill fins protected by a dark hide frame'],
 seals:['three little ivory wax dolls in a shallow brass sealing box','a small ivory charm pouch tied with red cord and a blue purification bead','a folded shed dark beast skin tucked into a loose crimson carrying pouch']
};
const air = {
 shield:['a wide oval violet deflection mirror in a brass rim with a small reflected star bolt','two intersecting translucent pale-blue barrier arcs surrounding an ivory charm','three overlapping broad rigid black feathers with silver edges on a bone plate'],
 sealed_cells:['a flat violet backup-personality tablet with one little ivory doll face','an open bronze spare-charm case holding two ivory sealing strips','a curled small ivory-and-red symbiotic sewing insect gripping two torn black feathers'],
 reserve_cells:['two flat collapsible purple glass storage flasks held in a leather harness','a small folded ivory wind sail on a bronze mast with a blue wind curl','a pear-shaped crimson dormant crop sac with a black feather collar'],
 wood_frame:['a thin angular wooden support frame fading partially into violet translucency','a folded ivory paper doll laid over a light bronze support truss','a light hollow ivory bird-bone truss beside a shed dark carapace'],
 fairing:['two short ivory wing panels pulled inward by three gold puppet strings','a swept-back bronze winglet wrapped in an ivory wind charm and blue current','a detached tapered black falcon wing section with a strong crimson muscle root'],
 thrust_assist:['a sharp violet levitation crystal in an open brass overdrive mount with a short purple trail','a bronze lift ring bearing three burning ivory charms and a blue rising current','a separate pair of short black feathered wings joined at a crimson muscle root'],
 cooling_flaps:['a six-petal violet crystal pressure-release flower on a small brass base','a low bronze purification ring with four ivory petals and one blue bead','three red organic breathing gills on a dark feathered mounting'],
 ballast_cage:['a small hanging wicker tea basket containing two ivory cups and a tiny teapot','a low bronze airborne offering platform holding one ivory charm and a blue bead','a compact black-iron rack holding a thick gray tooth-grinding stone'],
 signal_lamp:['a wide knotted loop of golden puppet string with a small glowing violet knot','a small red-and-bronze airborne prayer lantern suspended by a short ivory cord','two black feathers with glowing red moss growing along their barbs'],
 comfort:['a tiny ivory singing clockwork doll with an open mouth and a brass winding key','a small bronze airborne incense vessel with a hanging red cord and blue wisp','a curled dark soothing parasite wrapped gently around a small bone bead'],
 ornament:['a miniature folded violet theatrical curtain hanging from a brass rod','a short fan of colorful ritual pennants tied to a bronze rail','three long ornamental black tail feathers tipped with muted crimson'],
 satchel:['a folded ivory flying puppet with unpowered jointed wings tucked into a brown satchel','a plain wooden box packed with blank ivory prayer slips and tied with red cord','a hanging dark-red egg pouch holding two small dormant ivory beast eggs'],
 floats:['a flat violet mirror reflecting a tiny puppet silhouette beside a contained blue ripple','two ivory water-search charms stretched along a low bronze ski with blue ripples','a detached dark whisker pad with six long silver aquatic sensing whiskers'],
 aux_light:['two tiny winged ivory puppet star-shooters with purple crystal heads','a bronze ring with four pointed ivory tracking charms and a small blue target-like orb','three sharp black feather projectiles swirling around a crimson bead'],
 aux_heavy:['a broad spinning bronze disc bearing four violet crystal emitters around its rim','a triangular bronze interception rack bearing three ivory lightning charms','a dense black-feather weapon nest with six stiff silver spear-like feathers'],
 aux_cannon:['a long sharp triangular violet focusing prism in a light brass rail','a long bronze sky-thunder lance with ivory sealing strips and one blue spark','a long ivory bone javelin protruding from a thick crimson growth gland'],
 aux_scatter:['a squat wooden fireworks pot emitting three small violet starbursts','a wreath of folded ivory paper blossoms around a bronze charm ring','a sagging dark feather sac spilling four irregular loose black feathers'],
 aux_bombs:['a large cracked violet explosive crystal suspended in a simple brass bomb clamp','a short bundle of three ground-thunder charm packets tied with red cord','a cracked crimson explosive beast egg strapped into a black feather bomb clamp'],
 aux_rockets:['a narrow wooden launch case holding three pointed purple crystal star bolts','a row of three narrow ivory lightning charms on a bronze launch rail','two pointed crimson pursuit eggs with black feather fins on a dark launch rail'],
 aux_torpedo:['a tiny elongated ivory underwater puppet with a violet nose crystal and brass fins','a pointed ivory water-seeking charm wrapped around a slim bronze float','a long dark-red aquatic parasite egg with a bone nose and short black fins'],
 aux_camera:['a tiny ivory observation puppet head carrying a large bronze telescope eye','an ivory photographic tracing charm stretched over a small bronze optical frame','a dark-red eye pouch containing three amber compound eyes'],
 aux_mines:['a small sleeping ivory puppet curled around a violet crystal under a brass sealing cage','three drifting ivory water-sealing charms gathered around a flat bronze buoy','a round dormant dark-red aquatic egg sac encircled by short bone spines'],
 bomb_sight:['a tiny ivory prediction puppet looking through a compact brass sight over a wooden grid','a small bronze prayer anchor with four ivory charms and a blue aiming bead','a dark hunting snout fragment bearing five long downward-curving ivory whiskers'],
 navigation:['a tiny ivory memory doll holding a dark-blue star chart, simple abstract dots only','a small bronze homeward signpost with two arrow-shaped ivory charms','a crescent bone homing mark fitted between two folded black feathers'],
 intercept_eye:['a wide brass shadow-capture frame with a taut golden string grid and purple lens','a luminous blue barrier eye framed by a bronze crescent and two ivory charms','three luminous crimson hunting eyes clustered in a black feathered frame'],
 maritime_eye:['a tiny ivory seaward observation puppet holding a short brass telescope with a blue lens','a flat bronze ritual array carrying two ivory charms and three blue water-vein beads','a broad dark snout with many long ivory sea-sensing whiskers'],
 false_echo:['a chipped violet memory plate with a tiny ivory ear and broken brass contacts','a bamboo fortune cylinder with two loose wooden sticks and a red cord','a lone distracted amber third eye sitting crookedly in an oversized bone socket'],
 tail_sentry:['a tiny ivory rear-guard puppet seated behind a short violet star emitter','a swept-back bronze tail bracket carrying two ivory interception charms','one hooked crimson parasite tail ending in a small dark biting jaw'],
 paired_tail:['two small ivory rear-guard puppets seated back-to-back on a wooden bracket','two intersecting pale-blue tail barriers on a bronze frame bearing four ivory charms','two interwoven dark-red tails ending in separate black biting jaws'],
 blind_spot:['a small ivory guard puppet facing away from its backward-pointing purple emitter','an ivory guardian charm pointing sideways on a visibly crooked bronze bracket','a curled crimson parasite tail biting greedily at its own black energy sac']
};
const styles=['magic','wakan','demonforce'];
exports.subjectFor=function(conceptKey){
 const [kind,style,key]=conceptKey.split('/');
 const subject=(kind==='armor'?tank:air)[key]?.[styles.indexOf(style)];
 if(!subject)throw Error('Missing icon silhouette '+conceptKey);
 return subject;
};
