// Authored fantasy functions. Native modules supply ONLY slots, role metadata and placeholder art.
const C=(name,description,values,multiply={},missionStats=[],resources={})=>({name,description,values,multiply,missionStats,resources});
const M=(missions,values,averages)=>({missions,values,averages});
const ground=['cas','attack_logistics'],sea=['naval_bomber','port_strike'];
const bomber=['naval_bomber','port_strike','strategic_bomber','naval_patrol','cas','attack_logistics'];
const tank={
 radio_1:[
  C('单线操偶中继','把主操偶者的动作传给随伴人偶，改善进攻协同；维持术式增加能耗。',{build_cost_ic:.9,reliability:.025,fuel_consumption:.08},{breakthrough:.14}),
  C('守阵共鸣铃','御札共鸣维持守势阵形，增强防御，但移动中的突击协同较差。',{build_cost_ic:1,maximum_speed:-.1},{defense:.22,breakthrough:-.04}),
  C('兽群统御喉','用统御吼声驱使妖兽突进，突破提高，持续躁动降低可靠性。',{build_cost_ic:1,reliability:-.04},{breakthrough:.2,defense:-.05})
 ],
 radio_2:[
  C('并行操偶咒线','多路咒线同时控制火力节点，增加软攻与突破；线缆纠缠降低稳定性。',{build_cost_ic:1.9,soft_attack:1,fuel_consumption:.12,reliability:-.03},{breakthrough:.21}),
  C('轮转结界钟','把相邻符阵的缺口交替封住，提高防御和可靠性，行军时必须保持队形。',{build_cost_ic:2,reliability:.04,maximum_speed:-.25},{defense:.32}),
  C('战意回响骨鼓','鼓点放大兽群战意，进攻更凶猛，纪律与维护同时恶化。',{build_cost_ic:2.2,reliability:-.065},{soft_attack:.07,breakthrough:.27,defense:-.06})
 ],
 radio_3:[
  C('分布式人偶心智匣','多个计算人偶分担瞄准和操控，增强火力与突破；高密度回路昂贵而脆弱。',{build_cost_ic:3.4,reliability:-.055,fuel_consumption:.2},{breakthrough:.28,soft_attack:.08,defense:-.05}),
  C('大结界阵眼','以阵眼统合防护术式，守势收益高；占用能量并拖累进攻。',{build_cost_ic:3.2,maximum_speed:-.35,fuel_consumption:.15},{defense:.45,armor_value:.06,breakthrough:-.08}),
  C('百兽王令冠','集中兽群的攻击冲动，获得较高突破与火力；失控风险和能耗显著上升。',{build_cost_ic:3.5,reliability:-.1,fuel_consumption:.3},{breakthrough:.34,hard_attack:.09,defense:-.1})
 ],
 smoke:[
  C('替身人偶投放匣','投放空壳人偶干扰瞄准，增加防御与突破；携带替身和咒线使结构更复杂。',{defense:3,breakthrough:2.5,build_cost_ic:1.4,reliability:-.025}),
  C('折光御札障壁','改变弹道附近的光影以掩护车体，偏重防御，维持符阵会消耗动力。',{defense:4,breakthrough:.5,build_cost_ic:1.3,fuel_consumption:.12}),
  C('蜕壳诱饵囊','抛出带妖气的空壳诱饵，保留突击节奏，脱壳机构降低可靠性。',{defense:1.5,breakthrough:3,maximum_speed:.1,build_cost_ic:1.5,reliability:-.045})
 ],
 wet_storage:[
  C('魔晶隔离封棺','隔离失控魔晶以改善可靠性，封棺减慢能量释放，软攻略降。',{reliability:.11,soft_attack:-.6,build_cost_ic:1.7}),
  C('镇暴灵力封印','压低符弹的暴走频率，提高可靠性与防御；温和释放削弱突破。',{reliability:.08,defense:1,breakthrough:-1,build_cost_ic:1.5}),
  C('逆鳞抑制钉','抑制妖兽暴走，稳定性提升，但驯化后的攻击欲望有所下降。',{reliability:.12,soft_attack:-1,breakthrough:-.5,build_cost_ic:1.6})
 ],
 maintenance:[
  C('备用人格晶片','受损控制回路由备用人格接管，提高可靠性与协同；晶片价格高。',{reliability:.065,breakthrough:1,build_cost_ic:2.1}),
  C('断符续接阵','断裂符阵由备用御札续接，改善稳定性并略减维持能耗，占用额外空间。',{reliability:.075,fuel_consumption:-.04,maximum_speed:-.15,build_cost_ic:1.9}),
  C('活体接骨囊','活体结构封合细小裂口，以可靠性表示维护收益；再生组织增加能耗与负重。',{reliability:.09,fuel_consumption:.16,maximum_speed:-.2,build_cost_ic:2})
 ],
 secondary_mg:[
  C('袖珍随伴人偶群','随伴人偶从多个角度投射星弹，增加软攻和突破，代价是咒线负担。',{soft_attack:4,breakthrough:1.5,reliability:-.025,fuel_consumption:.08,build_cost_ic:2.3}),
  C('自动迎击御札环','御札在车体周围迎击近距离目标，火力较低但改善防御。',{soft_attack:2.5,defense:2.5,breakthrough:-.5,build_cost_ic:2}),
  C('寄生飞羽巢','寄生飞羽向近敌反复散射，软攻较高，持续生长消耗妖力并影响可靠性。',{soft_attack:5,reliability:-.04,fuel_consumption:.18,build_cost_ic:2.4})
 ],
 secondary_cannon:[
  C('折射魔晶副炮','晶体把一次投射分为多道弹幕，偏向软攻和突破，穿甲能力一般。',{soft_attack:6,hard_attack:1,breakthrough:1.5,reliability:-.07,build_cost_ic:4}),
  C('贯界御札副炮','集中符力贯穿局部防护，侧重穿甲和硬攻，射击间隙拉低突破。',{soft_attack:1.5,hard_attack:4,ap_attack:4,breakthrough:-1,build_cost_ic:3.9}),
  C('伸缩妖角副炮','妖角以冲击方式破坏近敌，硬攻较高，但额外活体关节降低可靠性。',{soft_attack:3,hard_attack:4.5,breakthrough:1,reliability:-.09,maximum_speed:-.2,build_cost_ic:4})
 ],
 secondary_howitzer:[
  C('魔力共振爆裂器','引发大范围魔力共振，软攻高，但能耗、造价和可靠性代价明显。',{soft_attack:9,breakthrough:-1,reliability:-.1,fuel_consumption:.4,maximum_speed:-.25,build_cost_ic:5}),
  C('连锁镇地雷符','雷符按次序震击地面，兼顾软攻与防御；布阵拖累突击速度。',{soft_attack:5,defense:2,maximum_speed:-.3,build_cost_ic:4.3}),
  C('孵化爆裂妖卵','抛出不稳定妖卵制造范围爆裂，软攻和少量硬攻增加，事故率高。',{soft_attack:7,hard_attack:1.5,reliability:-.12,build_cost_ic:4.5})
 ],
 secondary_lance:[
  C('单点坍缩魔晶针','牺牲弹幕覆盖集中魔力穿刺，穿甲高；聚焦器脆弱且昂贵。',{soft_attack:-.5,hard_attack:3,ap_attack:7,reliability:-.08,build_cost_ic:4.6}),
  C('破邪贯通钉','御札锁定一点进行贯穿，穿甲收益集中，持续锁定压低突破。',{soft_attack:.5,hard_attack:3.5,ap_attack:5,breakthrough:-1.5,build_cost_ic:3.8}),
  C('缠咬贯甲触腕','触腕抓附目标后穿刺装甲，硬攻较强；拖曳机构降低速度和可靠性。',{soft_attack:1,hard_attack:5,ap_attack:3.5,maximum_speed:-.4,reliability:-.07,build_cost_ic:4.1})
 ],
 secondary_aa:[
  C('环轨拦截人偶','沿车体环轨运行的小人偶负责仰角弹幕，附带少量掩护，能耗增加。',{air_attack:3,defense:1,soft_attack:-.5,fuel_consumption:.15,build_cost_ic:3.5}),
  C('落羽封空符阵','以封空符阵干扰低空目标，兼顾防御，但阵眼降低机动。',{air_attack:2.5,defense:1.5,maximum_speed:-.25,build_cost_ic:3.1}),
  C('捕风妖舌副座','弹射妖舌和硬羽拦截低空目标，对空收益有限且事故率高。',{air_attack:3.5,soft_attack:.5,reliability:-.09,build_cost_ic:3.4})
 ],
 secondary_flame:[
  C('失控魔力泄压口','把多余魔力向敌方泄放，提供软攻，可靠性与防护下降。',{soft_attack:7,reliability:-.12,armor_value:-.5,fuel_consumption:.25,build_cost_ic:4.4}),
  C('火行轮转符炉','持续轮换火行御札产生近距焰流，增加软攻，但损失速度并提高能耗。',{soft_attack:5.5,maximum_speed:-.35,fuel_consumption:.2,build_cost_ic:3.7}),
  C('灼息妖腺','妖腺喷出灼热吐息，软攻较高，但伤及活体结构，可靠性下降。',{soft_attack:7.5,reliability:-.1,defense:-1,fuel_consumption:.3,build_cost_ic:4})
 ],
 coax:[
  C('咒线缝合针','细小咒线束用于补充穿刺，硬攻略增，火力收益低。',{soft_attack:.5,hard_attack:1,build_cost_ic:1.6,reliability:-.02}),
  C('贴身驱邪札','贴身御札偏重近距离护卫，只提供很小的软攻与防御。',{soft_attack:.4,defense:1.4,breakthrough:-.2,build_cost_ic:1.3}),
  C('口器喷刺管','口器喷出少量妖刺，软攻略增，维护和能耗不划算。',{soft_attack:1.5,reliability:-.025,fuel_consumption:.08,build_cost_ic:1.8})
 ],
 stabilizer:[
  C('动作预演人偶','计算人偶预演下一步动作，提高突破，复杂预演耗能并降低防御。',{breakthrough:5,defense:-1,fuel_consumption:.15,build_cost_ic:3.2}),
  C('定心阵眼','稳定御札阵列，提高防御与可靠性，快速移动时必须降低速度。',{defense:3,reliability:.03,maximum_speed:-.3,build_cost_ic:2.9}),
  C('猎食瞄准复眼','多枚复眼协调咬击方向，提高突破和少量硬攻，内部拥挤影响稳定性。',{breakthrough:3,hard_attack:1,reliability:-.04,build_cost_ic:3})
 ],
 sloped_shield:[
  C('折返魔力镜面','魔纹镜面增强装甲表现，维持反射术式消耗能量并降低稳定性。',{build_cost_ic:2.8,fuel_consumption:.14,reliability:-.03},{armor_value:.16,defense:-.04}),
  C('层叠护身结界','多层符阵增加装甲与防御；维持阵形牺牲速度和突破。',{build_cost_ic:3,maximum_speed:-.3},{armor_value:.12,defense:.1,breakthrough:-.07}),
  C('石化妖皮层','局部妖皮硬化，装甲提升明显，僵硬皮层削弱速度与可靠性。',{build_cost_ic:2.7,maximum_speed:-.4,reliability:-.04},{armor_value:.2})
 ],
 skirts:[
  C('悬浮人偶护盾片','悬浮护片补充防御，外露控制线增加维持能耗。',{armor_value:1,defense:3,fuel_consumption:.13,build_cost_ic:2.4}),
  C('四方结界幡','四方御札增加防御和少量装甲，阵幡拖慢车体。',{armor_value:1.5,defense:3.5,maximum_speed:-.3,build_cost_ic:2.2}),
  C('侧生护体骨刺','侧生骨刺提高装甲并补充近敌火力，负担降低可靠性。',{armor_value:2,soft_attack:.8,reliability:-.045,maximum_speed:-.25,build_cost_ic:2.6})
 ],
 extra_magazine:[
  C('危险魔晶串联匣','串联魔晶提高投射强度，但不稳定串联显著降低可靠性。',{build_cost_ic:2.1,reliability:-.13,fuel_consumption:.25},{soft_attack:.09,hard_attack:.06}),
  C('一次性愿力符库','预存御札改善防御和突破，储存大量未释放符力增加故障风险。',{defense:3,breakthrough:2,reliability:-.08,build_cost_ic:1.9}),
  C('狂化营养腺','刺激攻击性组织生长，提高软攻，失控风险和补充消耗明显。',{build_cost_ic:2,reliability:-.14,fuel_consumption:.3},{soft_attack:.12,defense:-.05})
 ],
 dozer:[
  C('挖坑小人偶收纳箱','小人偶协助整理阵地，堑壕收益有限；携带人偶牺牲速度。',{entrenchment:.5,maximum_speed:-.25,reliability:-.02,build_cost_ic:2.2}),
  C('镇土阵脚','阵脚压实阵地，提高堑壕与少量防御，移动时拖累机动。',{entrenchment:.7,defense:.5,maximum_speed:-.4,build_cost_ic:2.1}),
  C('掘穴前肢','前肢便于掘穴和近敌扑击，增加堑壕与少量软攻，维护不便。',{entrenchment:.4,soft_attack:.6,reliability:-.05,maximum_speed:-.3,build_cost_ic:2.3})
 ],
 fuel_drum:[
  C('压缩魔力瓶','压缩魔力增加携行储备并略减维持消耗，压力容器降低可靠性。',{fuel_capacity:60,fuel_consumption:-.04,reliability:-.045,build_cost_ic:2}),
  C('蓄愿御札匣','预存愿力延长动力储备，厚重符匣拖慢车体。',{fuel_capacity:80,maximum_speed:-.45,build_cost_ic:1.9}),
  C('休眠妖力胃囊','胃囊储备妖力，但维持活性会增加日常消耗和结构负担。',{fuel_capacity:100,fuel_consumption:.1,reliability:-.04,maximum_speed:-.3,build_cost_ic:2.2})
 ],
 toolbox:[
  C('咒线梳理小人偶','小人偶梳理缠绕咒线，可靠性和突破收益很小，仍需供能。',{reliability:.012,breakthrough:.2,fuel_consumption:.05,build_cost_ic:1.4}),
  C('御札晾晒架','晾晒御札只能稍微改善可靠性，外置架降低速度。',{reliability:.018,maximum_speed:-.2,build_cost_ic:1.1}),
  C('寄生清洁虫盒','清洁虫清除少量寄生组织，以很小稳定性收益换取额外能耗。',{reliability:.02,fuel_consumption:.07,build_cost_ic:1.3})
 ],
 signal_flags:[
  C('弹幕舞步谱架','按谱表协调表演式弹幕，少量软攻和突破难以抵消空间开销。',{soft_attack:.25,breakthrough:.25,armor_value:-.3,build_cost_ic:1.1}),
  C('祈愿签筒','签筒帮助阵员保持心境，仅有少量防御收益。',{defense:.6,breakthrough:-.2,build_cost_ic:1}),
  C('威吓兽牙旗','兽牙旗激发短暂攻击冲动，软攻略增而防御略减。',{soft_attack:.5,defense:-.3,build_cost_ic:1.2})
 ],
 ornamental_armor:[
  C('操偶音乐盒','音乐盒维持操偶节拍，协同收益微小，精密盒体昂贵。',{breakthrough:.25,reliability:.005,build_cost_ic:1.8,fuel_consumption:.04}),
  C('结界风铃串','风铃帮助辨认符阵边缘，防御收益很小，悬挂物妨碍机动。',{defense:.6,maximum_speed:-.15,build_cost_ic:1.6}),
  C('炫耀用第二对角','第二对角主要用于威吓，少量软攻无法抵消负重。',{soft_attack:.4,armor_value:.3,maximum_speed:-.35,build_cost_ic:1.9})
 ],
 parade_lights:[
  C('幻影舞台投射器','投射表演幻影，小幅扰乱瞄准，控制回路增加事故与能耗。',{defense:.4,breakthrough:.3,reliability:-.02,fuel_consumption:.1,build_cost_ic:1.4}),
  C('祭典供奉灯','祭典灵灯稳定少量符力，只有微弱防御与可靠性收益。',{defense:.3,reliability:.005,build_cost_ic:1.3}),
  C('发光妖苔培养盘','妖苔帮助识别伙伴，微小协同收益伴随维持消耗。',{breakthrough:.3,fuel_consumption:.08,reliability:-.01,build_cost_ic:1.2})
 ],
 crew_comfort:[
  C('人偶茶会托盘','操偶间隙举行微型茶会，稳定性改善微乎其微，托盘占用防护空间。',{reliability:.01,armor_value:-.4,build_cost_ic:1.5}),
  C('静心香炉','香气有助于保持符阵，只提供小幅可靠性，增加供能需求。',{reliability:.015,fuel_consumption:.05,build_cost_ic:1.4}),
  C('御兽磨牙石','磨牙石降低一点躁动，也稍微削弱攻击欲望。',{reliability:.018,soft_attack:-.3,build_cost_ic:1.2})
 ],
 spare_tracks:[
  C('未上弦人偶备队','备队携带少量替换关节和火力节点，收益小，体积与重量大。',{reliability:.018,soft_attack:.4,maximum_speed:-.4,build_cost_ic:2.3}),
  C('未开光符纸箱','大量备用符纸仅改善一点阵地防御，携行负担明显。',{defense:.7,reliability:.005,maximum_speed:-.3,build_cost_ic:1.8}),
  C('休眠替换肢囊','休眠肢体用于维护，可靠性收益有限，维持组织需要能量。',{reliability:.025,fuel_consumption:.1,maximum_speed:-.3,build_cost_ic:2})
 ],
 emergency_battery:[
  C('禁制第二魔力核','第二魔力核增幅速度与火力，但可靠性、能耗和造价代价很高。',{reliability:-.12,fuel_consumption:.45,build_cost_ic:3},{maximum_speed:.08,soft_attack:.05}),
  C('焚符急行阵','焚烧备用御札提高速度，释放过程中防御和稳定性下降。',{reliability:-.07,fuel_consumption:.3,build_cost_ic:2.5},{maximum_speed:.1,defense:-.08}),
  C('狂猎催化腺','催化腺驱动妖兽高速扑击，速度和突破增加，但极不稳定。',{reliability:-.15,fuel_consumption:.4,build_cost_ic:2.8},{maximum_speed:.12,breakthrough:.06})
 ],
 cooling_fins:[
  C('魔力泄流梳','泄放积累魔力来稳定核心，可靠性提高，武器输出略降。',{reliability:.055,soft_attack:-.7,build_cost_ic:1.9}),
  C('散愿平衡环','把过剩愿力导回符阵，防御略增，移动速度降低。',{reliability:.035,defense:1,maximum_speed:-.3,build_cost_ic:1.8}),
  C('妖血换热腮','换热组织改善稳定性，额外供养提高能耗。',{reliability:.06,fuel_consumption:.15,maximum_speed:-.15,build_cost_ic:2.1})
 ],
 seals:[
  C('备用封印蜡偶','蜡偶堵塞少量回路缺口，只提供很小的装甲与稳定性。',{reliability:.012,armor_value:.4,maximum_speed:-.15,build_cost_ic:1.5}),
  C('避秽净化札袋','净化札减轻符具污染，可靠性收益有限，消耗少量维持动力。',{reliability:.022,fuel_consumption:.04,build_cost_ic:1.3}),
  C('蜕皮收纳囊','保留旧皮保护局部结构，防护很少，收纳囊妨碍机动。',{armor_value:.6,reliability:.01,maximum_speed:-.25,build_cost_ic:1.6})
 ]
};

// Base values scale by small/medium/large size, while reliability and percentage effects do not.
const sized={
 shield:[
  C('弹幕偏转镜','偏转镜把防护与拦截能力绑在一起；镜面脆弱，防护收益以稳定性换取。',{air_defence:2,air_attack:.5,weight:1.2,build_cost_ic:1.8,reliability:-.025}),
  C('重叠守护结界','厚重结界提高空防，持续维持会压低航程与机动。',{air_defence:3,weight:1,build_cost_ic:2,air_agility:-1},{air_range:-.07}),
  C('硬化妖羽层','妖羽硬化增加空防，但柔韧性下降，转向更笨重。',{air_defence:2.5,weight:1.5,build_cost_ic:1.7,air_agility:-1.5})
 ],
 sealed_cells:[
  C('备用操偶人格','备用人格接替失灵操控，提供可靠性与机动；额外回路耗能。',{reliability:.065,air_agility:1,weight:.75,build_cost_ic:2.2,fuel_consumption:.06}),
  C('断界续符匣','备用符阵填补防护缺口，空防与稳定性改善，持续布阵耗能。',{air_defence:2.5,reliability:.04,weight:.8,build_cost_ic:2.1,fuel_consumption:.08}),
  C('缝翼共生虫','共生虫封合细小结构损伤，以可靠性表示维护收益；不恢复战斗中的飞机数量。',{air_defence:1,reliability:.085,weight:1,build_cost_ic:2.2,fuel_consumption:.12})
 ],
 reserve_cells:[
  C('折叠魔力储瓶','压缩魔力增加航程，泄漏风险降低可靠性，储瓶防护薄弱。',{air_defence:-1,reliability:-.045,weight:1.5,build_cost_ic:2.1},{air_range:.3}),
  C('顺风愿力帆','借助御风符延长航程，附带阻力和机动代价。',{weight:1.3,build_cost_ic:2.2,air_agility:-1},{air_range:.24,maximum_speed:-.05}),
  C('休眠蓄力嗉囊','嗉囊储备妖力，提高航程，活体补给机构拖累速度并增加能耗。',{weight:2,build_cost_ic:2,fuel_consumption:.1},{air_range:.32,maximum_speed:-.07})
 ],
 wood_frame:[
  C('半虚化承重咒','暂时削弱实体结构以减轻重量；防护与可靠性明显下降，维持咒术仍需成本。',{weight:-1,air_defence:-2,reliability:-.055,build_cost_ic:2,fuel_consumption:.08}),
  C('纸替身承重符','用纸替身承担部分重量，载重减轻，防护下降，符阵可靠性受损。',{weight:-.7,air_defence:-1.5,reliability:-.045,build_cost_ic:1.8}),
  C('蜕壳轻骨术','舍弃厚重表层来减轻重量，提高少量机动，防护与稳定性下降。',{weight:-1.1,air_defence:-2.5,reliability:-.065,air_agility:.5,build_cost_ic:1.7})
 ],
 fairing:[
  C('咒线牵引翼','咒线辅助转向，机动提高；暴露的牵引线影响防护和稳定性。',{air_agility:2,air_defence:-1,reliability:-.02,weight:.6,build_cost_ic:2}),
  C('逆风转向符','御风符协助急转，机动提高，但航程与速度有所损失。',{air_agility:2.5,weight:.5,build_cost_ic:2.1},{air_range:-.06,maximum_speed:-.025}),
  C('猎隼俯冲翼肌','翼肌偏重快速扑击，速度提高，航程与可靠性降低。',{weight:.8,build_cost_ic:2.2,reliability:-.035},{maximum_speed:.065,air_range:-.08})
 ],
 thrust_assist:[
  C('过载御空魔晶','过载魔晶提供额外推力和少量火力，可靠性损失大，能耗高。',{thrust:3,weight:1,air_attack:.8,reliability:-.09,fuel_consumption:.2,build_cost_ic:3}),
  C('焚符升力阵','燃烧御札维持额外升力，以推力属性表示；航程和可靠性下降。',{thrust:2.5,weight:.8,reliability:-.055,fuel_consumption:.16,build_cost_ic:2.8},{air_range:-.1}),
  C('第二对妖翼','额外妖翼提高推力并略增空防，体积与供养负担显著。',{thrust:4,weight:2,air_defence:.5,reliability:-.07,fuel_consumption:.22,build_cost_ic:3.2},{maximum_speed:-.035})
 ],
 cooling_flaps:[
  C('魔力泄压花','花瓣导出不稳定魔力，可靠性增加，投射武器的输出下降。',{reliability:.055,weight:.7,build_cost_ic:1.7},{air_attack:-.04}),
  C('散愿净心环','净心环稳定符阵，可靠性略增并减轻一点夜间惩罚，速度下降。',{reliability:.035,night_penalty:-.025,weight:.8,build_cost_ic:1.8},{maximum_speed:-.03}),
  C('妖血呼吸腮','呼吸腮改善活体稳定性，增加能耗与外形阻力。',{reliability:.07,fuel_consumption:.12,weight:1,build_cost_ic:1.9},{maximum_speed:-.045})
 ],
 ballast_cage:[
  C('飞行茶会吊篮','吊篮供操偶者短暂休息，稳定性收益微小，负重和阻力明显。',{reliability:.012,weight:2,air_agility:-1,build_cost_ic:1.8}),
  C('浮空供奉台','供奉台维持微弱防护，重量和造价与收益不成比例。',{air_defence:.5,weight:2,build_cost_ic:1.9},{maximum_speed:-.02}),
  C('空中磨牙架','磨牙架降低一点躁动，也削弱攻击欲望，并显著增加重量。',{reliability:.018,weight:2,build_cost_ic:1.6},{air_attack:-.03})
 ],
 signal_lamp:[
  C('荧光咒线结','荧光咒线提供少量夜间协同，维持耗能和重量仍然存在。',{night_penalty:-.025,weight:.6,fuel_consumption:.03,build_cost_ic:1.3}),
  C('空中祈愿灯','祈愿灯减轻少量夜间惩罚并提供微弱防护，悬挂物造成阻力。',{night_penalty:-.02,air_defence:.2,weight:.8,build_cost_ic:1.5},{maximum_speed:-.02}),
  C('发光妖苔羽','妖苔有助辨认同伴，夜间收益很小，额外活体组织消耗妖力。',{night_penalty:-.015,weight:.6,fuel_consumption:.05,build_cost_ic:1.2})
 ],
 comfort:[
  C('袖珍歌唱人偶','歌唱节奏稳定操控，可靠性收益很小，机动略受干扰。',{reliability:.012,air_agility:-.2,weight:.7,build_cost_ic:1.6}),
  C('空中静心香炉','静心香炉小幅改善符阵稳定性，释放香气消耗维持能量。',{reliability:.018,fuel_consumption:.04,weight:.6,build_cost_ic:1.5}),
  C('安抚寄生虫','安抚虫降低一点狂躁，也压低少量攻击欲望。',{reliability:.02,weight:.7,build_cost_ic:1.3},{air_attack:-.035})
 ],
 ornament:[
  C('幻影舞台帷幕','帷幕幻影略微扰乱敌方瞄准，控制负担和阻力远大于防护收益。',{air_defence:.3,reliability:-.015,weight:1.2,build_cost_ic:1.9},{maximum_speed:-.03}),
  C('七彩祭典符幡','祭典符幡提供很小防护，显著拖累急转。',{air_defence:.4,air_agility:-1.2,weight:1,build_cost_ic:1.7}),
  C('炫耀用长尾羽','长尾羽用于展示威仪，只增加一点空攻，机动与阻力代价明显。',{air_attack:.4,air_agility:-1.5,weight:1.2,build_cost_ic:1.8},{maximum_speed:-.025})
 ],
 satchel:[
  C('未上弦飞行人偶','备用人偶提供少量稳定性，携行收益很低。',{reliability:.01,weight:1.2,build_cost_ic:1.8}),
  C('未开光御札箱','备用符纸略增航程，但箱体重量远大于续航收益。',{air_range:15,weight:1.3,build_cost_ic:1.5}),
  C('休眠妖卵袋','休眠妖卵略增携行储备，维持组织消耗妖力。',{air_range:20,fuel_consumption:.04,weight:1.4,build_cost_ic:1.6})
 ],
 floats:[
  C('水面倒影诱饵','水面幻影掩护海上搜索，任务中稍增空防与探测，其他任务只承担负重。',{weight:1.5,build_cost_ic:2.3},{maximum_speed:-.08},[M(['naval_patrol','naval_bomber'],{surface_detection:3,air_defence:1})]),
  C('踏浪索敌符','御札沿水面传播探测术式，偏重潜艇搜索，传导阵增加阻力。',{weight:1.3,build_cost_ic:2.4},{maximum_speed:-.09},[M(['naval_patrol','naval_bomber'],{surface_detection:2,sub_detection:2})]),
  C('水栖感知胡须','感知胡须提高海上探测，柔软外形拖累转向和速度。',{weight:1.8,air_agility:-1.5,build_cost_ic:2.2},{maximum_speed:-.1},[M(['naval_patrol','naval_bomber'],{surface_detection:4,sub_detection:1})])
 ]
};

const other={
 aux_light:[
  C('随伴星弹人偶','随伴人偶提供对空火力和一点机动，维持操控消耗能量，防护略减。',{air_attack:5,air_agility:.5,air_defence:-.5,weight:1,build_cost_ic:2,fuel_consumption:.05}),
  C('追踪御札环','御札在截击任务中追踪目标，常态火力较低，截击时额外提高空攻。',{air_attack:3,air_defence:.5,weight:1,build_cost_ic:2},{},[M(['interception'],{air_attack:2.5})]),
  C('噬风飞羽群','飞羽偏重近距离扑击，空攻较高，但重量和航程代价明显。',{air_attack:6.5,weight:1.8,build_cost_ic:2.3,reliability:-.025},{air_range:-.045})
 ],
 aux_heavy:[
  C('回旋魔晶弹幕盘','魔晶盘集中对空弹幕，火力与防护稍增，可靠性下降。',{air_attack:9,air_defence:1,weight:3.2,build_cost_ic:3.4,reliability:-.055}),
  C('雷札迎击阵','雷札偏重截击，平时火力一般，截击时增强空攻并减轻夜间惩罚。',{air_attack:5,weight:2.8,build_cost_ic:3.2},{},[M(['interception'],{air_attack:4,night_penalty:-.06})]),
  C('硬羽暴射巢','硬羽快速生长并射出，高空攻伴随机动与供养代价。',{air_attack:10,air_agility:-1,weight:3.6,build_cost_ic:3.1,fuel_consumption:.12})
 ],
 aux_cannon:[
  C('聚焦魔力棱镜','棱镜集中魔力贯射，空攻很高，持续聚焦降低防护与可靠性。',{air_attack:15,air_defence:-1,reliability:-.075,weight:4.5,build_cost_ic:4.8}),
  C('贯空雷符枪','集中雷符用于迎击，常态火力有限，截击时增强贯射能力。',{air_attack:8,air_agility:-.5,weight:3.8,build_cost_ic:4.2},{},[M(['interception'],{air_attack:4})]),
  C('妖骨投枪腺','大幅生长的妖骨作为投射物，空攻高，粗重腺体削弱机动与稳定性。',{air_attack:13,air_agility:-3,reliability:-.07,weight:4.8,build_cost_ic:4.4})
 ],
 aux_scatter:[
  C('表演型星弹烟花','烟花偏重图案与色彩，对空收益低，装置笨重且不稳定。',{air_attack:2.5,weight:3,build_cost_ic:3,reliability:-.045}),
  C('散华御札花环','花环御札提供少量护卫火力，防护和空攻都很有限。',{air_attack:1.5,air_defence:.5,weight:2.8,build_cost_ic:2.7}),
  C('散乱脱羽囊','脱羽乱射干扰近敌，空攻收益小，机动与稳定性代价大。',{air_attack:3,air_agility:-1,reliability:-.04,weight:3.3,build_cost_ic:2.8})
 ],
 aux_bombs:[
  C('共振爆裂魔晶','对地任务中触发连锁爆裂，高对地攻击伴随重量、机动和可靠性代价。',{build_cost_ic:2.8,reliability:-.06},{},[M(ground,{air_ground_attack:6,weight:4,air_agility:-8}),M(['naval_bomber'],{naval_strike_attack:1,weight:4,air_agility:-8},{naval_strike_targetting:2})]),
  C('镇地连锁雷札','对地雷札提高支援火力并掩护攻击姿态，对海收益很低。',{build_cost_ic:2.6},{},[M(ground,{air_ground_attack:4,air_defence:2,weight:3.5,air_agility:-7}),M(['naval_bomber'],{naval_strike_attack:1,weight:3.5},{naval_strike_targetting:1})]),
  C('孵化爆裂妖卵','妖卵对地爆裂猛烈，重载、能耗和事故风险显著。',{build_cost_ic:2.7,fuel_consumption:.15,reliability:-.08},{},[M(ground,{air_ground_attack:7,weight:5,air_agility:-11}),M(['naval_bomber'],{naval_strike_attack:1.5,weight:5,air_agility:-11},{naval_strike_targetting:1})])
 ],
 aux_rockets:[
  C('分裂星弹投射匣','支援任务中分裂星弹形成弹幕，兼顾少量护卫，但比简单挂架昂贵。',{build_cost_ic:3.1},{},[M(ground,{air_ground_attack:4,air_defence:1,weight:3,air_agility:-2})]),
  C('引雷御札串','御札串在对地任务中引导雷击，载荷较轻，火力收益中等。',{build_cost_ic:3},{},[M(ground,{air_ground_attack:3.5,weight:2.2,air_agility:-1})]),
  C('妖羽追击卵','对地任务投放追击妖卵，火力较高，生物载荷增加供养消耗。',{build_cost_ic:3,fuel_consumption:.1,reliability:-.04},{},[M(ground,{air_ground_attack:5,weight:3.8,air_agility:-4})])
 ],
 aux_torpedo:[
  C('潜行魔晶人偶','水下推进人偶偏重集中攻击，对海火力高但命中一般、载荷重。',{build_cost_ic:6.2,reliability:-.04},{},[M(sea,{naval_strike_attack:11,weight:6,air_agility:-12},{naval_strike_targetting:3})]),
  C('逐水索敌符','索敌符偏重命中与海面搜索，单次攻击较弱。',{build_cost_ic:5.8},{},[M(sea,{naval_strike_attack:6,surface_detection:2,weight:4.5,air_agility:-8},{naval_strike_targetting:6})]),
  C('寄生水栖妖卵','水栖妖卵近敌爆裂，火力高，命中与可靠性较差。',{build_cost_ic:5.9,reliability:-.075,fuel_consumption:.12},{},[M(sea,{naval_strike_attack:12,weight:6.5,air_agility:-14},{naval_strike_targetting:2})])
 ],
 aux_camera:[
  C('远视侦察人偶','侦察任务由远视人偶辅助，略减夜间惩罚，咒线耗能。',{weight:1.8,build_cost_ic:2.2,fuel_consumption:.04},{},[M(['recon'],{night_penalty:-.06})]),
  C('留影索迹符','索迹符在侦察时稳定观察，提供少量空防，不增加情报点倍率。',{weight:1.6,build_cost_ic:2.1},{},[M(['recon'],{air_defence:1,night_penalty:-.025})]),
  C('猎目复眼囊','复眼支持侦察并补充海面感知，敏感组织削弱可靠性。',{weight:2,build_cost_ic:2.3,reliability:-.03,surface_detection:1.5})
 ],
 aux_mines:[
  C('休眠魔晶伏偶','伏偶布雷效率低，复杂封印增加成本与事故率。',{mines_planting:.018,weight:3.5,build_cost_ic:3.8,reliability:-.02}),
  C('漂流封水御札','漂流御札用于低效率布雷，额外符阵仅改善一点海上防护。',{mines_planting:.014,weight:3,build_cost_ic:3.5},{},[M(['naval_mines_planting'],{air_defence:.5})]),
  C('沉睡水栖卵囊','卵囊布雷略快，但重载、供养与稳定性代价不划算。',{mines_planting:.025,weight:4,build_cost_ic:3.9,fuel_consumption:.07,reliability:-.045})
 ],
 bomb_sight:[
  C('轰炸预演小人偶','人偶预演轰炸落点，提高轰炸能力，计算回路耗能。',{air_bombing:3.5,weight:1.2,build_cost_ic:2.1,fuel_consumption:.05}),
  C('定点愿力锚','愿力锚偏重夜间轰炸引导，常态轰炸增益较小。',{air_bombing:1.5,weight:1,build_cost_ic:2},{},[M(['strategic_bomber'],{night_penalty:-.1,air_bombing:1})]),
  C('猎地感知须','感知须提高轰炸攻击，低空观察姿态降低防护。',{air_bombing:4,air_defence:-1,weight:1.5,build_cost_ic:2.2})
 ],
 navigation:[
  C('星图记忆人偶','记忆人偶偏重航程管理，只有少量夜间协同收益。',{air_range:45,night_penalty:-.04,weight:1.5,build_cost_ic:2.3}),
  C('归途愿力路标','路标减轻夜间惩罚并补充少量航程，维持术式消耗动力。',{air_range:20,night_penalty:-.1,fuel_consumption:.05,weight:1.3,build_cost_ic:2.2}),
  C('归巢本能印记','强化归巢本能增加航程，但攻击欲望被压低。',{air_range:60,weight:1.6,build_cost_ic:2.2},{air_attack:-.03})
 ],
 intercept_eye:[
  C('咒线捕影仪','截击时捕捉目标轨迹，提高少量空攻并减轻夜间惩罚，常态仅承担负重。',{weight:2.2,build_cost_ic:3.7},{},[M(['interception'],{air_attack:2,night_penalty:-.1})]),
  C('夜空结界眼','截击时以结界感知目标，夜间和空防收益较好，但火力增益很小。',{weight:1.9,build_cost_ic:3.6},{},[M(['interception'],{night_penalty:-.17,air_defence:1})]),
  C('夜猎妖眼簇','复眼提高夜间截击火力，敏感组织降低可靠性。',{weight:2.5,build_cost_ic:3.5,reliability:-.04},{},[M(['interception'],{air_attack:3,night_penalty:-.07})])
 ],
 maritime_eye:[
  C('海面远视人偶','海上任务中识别水面目标，潜艇探测一般；操控人偶需要持续供能。',{weight:2.2,build_cost_ic:3.4,fuel_consumption:.05},{},[M(['naval_bomber','port_strike','naval_patrol'],{surface_detection:8,sub_detection:1.5})]),
  C('水脉探知符阵','沿水脉识别水下目标，偏重潜艇探测，不增强轰炸火力。',{weight:2,build_cost_ic:3.3},{},[M(['naval_bomber','port_strike','naval_patrol'],{surface_detection:4,sub_detection:5})]),
  C('猎海感知须群','海上搜索感知强，感知须增加阻力与活体维护风险。',{weight:2.7,build_cost_ic:3.5,reliability:-.035},{maximum_speed:-.025},[M(['naval_bomber','port_strike','naval_patrol'],{surface_detection:10,sub_detection:2})])
 ],
 false_echo:[
  C('幻听记忆晶片','陈旧晶片只改善一点夜间截击，重量与能耗高于收益。',{weight:2,build_cost_ic:2.8,fuel_consumption:.03},{},[M(['interception'],{night_penalty:-.02})]),
  C('占卜签筒','占卜签只能提供极小夜间护卫收益，几乎不影响火力。',{weight:1.8,build_cost_ic:2.7},{},[M(['interception'],{night_penalty:-.015,air_defence:.2})]),
  C('多余第三只眼','第三只眼的注意力不集中，截击火力收益很小且影响机动。',{weight:2.2,build_cost_ic:2.9,air_agility:-.4},{},[M(['interception'],{air_attack:.3,night_penalty:-.01})])
 ],
 tail_sentry:[
  C('后向守卫人偶','守卫人偶兼顾防护与后向弹幕，轰炸和支援姿态稍稳，代价是咒线供能。',{air_attack:1.5,air_defence:.8,weight:1.8,build_cost_ic:2.3,fuel_consumption:.04},{maximum_speed:-.035},[M(bomber,{air_agility:.6})]),
  C('尾部迎击御札','尾部御札偏重防护，空攻低，外置符架增加阻力。',{air_attack:.5,air_defence:2,weight:1.5,build_cost_ic:2.2},{maximum_speed:-.045},[M(bomber,{air_agility:.2})]),
  C('反咬寄生尾','寄生尾偏重反咬火力，灵活性和可靠性较差。',{air_attack:2,air_defence:.5,weight:2.2,build_cost_ic:2.4,reliability:-.035},{maximum_speed:-.04},[M(bomber,{air_agility:.3})])
 ],
 paired_tail:[
  C('双体守卫人偶','两具守卫人偶交叉投射，火力与少量防护提高，计算供能负担大。',{air_attack:3.5,air_defence:1.5,weight:3.8,build_cost_ic:4.3,fuel_consumption:.1},{maximum_speed:-.07},[M(bomber,{air_agility:1})]),
  C('双层尾部结界','交叠结界偏重防护，空攻有限，阵架笨重。',{air_attack:1,air_defence:4,weight:3.2,build_cost_ic:4.1},{maximum_speed:-.09},[M(bomber,{air_agility:.4})]),
  C('双生反咬尾','双尾同时反击，空攻高，活体冲突降低稳定性。',{air_attack:4.5,air_defence:1,weight:4.4,build_cost_ic:4.4,reliability:-.065},{maximum_speed:-.08},[M(bomber,{air_agility:.5})])
 ],
 blind_spot:[
  C('背对敌人的小人偶','人偶常把敌人认错方向，只有微弱自卫火力，咒线仍需供能。',{air_attack:.4,air_defence:.2,weight:2.3,build_cost_ic:2.9,fuel_consumption:.04},{maximum_speed:-.06}),
  C('方向错置的守护札','守护方向偏离要害，防护收益低，御札架造成阻力。',{air_attack:.1,air_defence:.5,weight:2,build_cost_ic:2.8},{maximum_speed:-.065}),
  C('抢食寄生尾','寄生尾更关心争夺能量，火力少，影响机动与供养。',{air_attack:.6,air_defence:.1,air_agility:-.5,weight:2.5,build_cost_ic:3,fuel_consumption:.07},{maximum_speed:-.055})
 ]
};

exports.specialize=function(base,style,kind){
 const index={magic:0,wakan:1,demonforce:2}[style],key=base.size?base.key.slice(0,-base.size.length-1):base.key;
 const table=kind==='armor'?tank:base.size?sized:other,concept=table[key]?.[index];
 if(!concept)throw Error('Missing authored Touhou module concept '+kind+'/'+style+'/'+key);
 const scale=base.size?{small:1,medium:2,large:3}[base.size]:1;
 const scaledKeys=new Set(['build_cost_ic','weight','thrust','air_defence','air_attack','air_agility','air_range','surface_detection','sub_detection','fuel_consumption']);
 const scaleValues=values=>Object.fromEntries(Object.entries(values||{}).map(([k,v])=>[k,Number((v*(scaledKeys.has(k)?scale:1)).toFixed(6))]));
 return {...base,...structuredClone(concept),values:scaleValues(concept.values),missionStats:concept.missionStats.map(m=>({...structuredClone(m),values:scaleValues(m.values),...(m.averages?{averages:scaleValues(m.averages)}:{})})),variants:undefined,
  conceptKey:kind+'/'+style+'/'+key,identity:({magic:'人偶协同与魔力过载',wakan:'结界守护与符阵引导',demonforce:'活体异变与狂猎火力'})[style]};
};
