const fs=require('fs'),path=require('path'),assert=require('assert');
const h=require('./hoi4_script.cjs'),{scalar:S,children:C}=h;
const root=path.resolve(__dirname,'..'),game=process.argv[2]||'F:/SteamLibrary/steamapps/common/Hearts of Iron IV';
const manifest=JSON.parse(fs.readFileSync(path.join(root,'docs/幻想乡军事原版化迁移清单.json'),'utf8'));
const baseline=JSON.parse(fs.readFileSync(path.join(root,'tools/military_migration_baseline.json'),'utf8'));
const values=JSON.parse(fs.readFileSync(path.join(root,'docs/幻想乡装备实际数值对照.json'),'utf8'));
const oldCards=h.parse(baseline.sources['common/technologies/touhou_trump_card.txt'])[0].value.filter(n=>n.key&&Array.isArray(n.value)).map(n=>n.key);
const retired=new Set([...Object.keys(manifest.units),...Object.keys(manifest.archetypes),...Object.keys(manifest.technologies),...oldCards,...Object.keys(manifest.armor?.replacements||{}),...Object.keys(manifest.aircraft?.replacements||{})]);
const errors=[],warnings=[];let checkedFiles=0,numericChecks=0;
const localEq=h.definitions(root,'common/units/equipment','equipments'),vanillaEq=h.definitions(game,'common/units/equipment','equipments');
const eq=new Map([...vanillaEq,...h.definitions(game,'common/units/equipment','duplicate_archetypes'),...localEq].map(n=>[n.key,n]));
const nativeEquipmentIds=new Set([...vanillaEq,...h.definitions(game,'common/units/equipment','duplicate_archetypes')].map(n=>n.key));
// Vanilla role chassis/airframes are generated by duplicate_archetypes, not explicit definitions.
for(const d of h.definitions(game,'common/units/equipment','duplicate_archetypes'))if(S(d,'only_duplicate_archetype')!=='yes'){
  const a=S(d,'archetype');for(const n of vanillaEq.filter(n=>S(n,'archetype')===a&&n.key.startsWith(a))) {
    const key=d.key+n.key.slice(a.length);eq.set(key,{...n,key});nativeEquipmentIds.add(key);
  }
}
const units=new Map(h.definitions(game,'common/units','sub_units').map(n=>[n.key,n]));
require('./armor_validation.cjs').installArmorAliases(manifest,eq);
require('./aircraft_validation.cjs').installAircraftAliases(manifest,eq);
const nativeSupport=id=>S(units.get(id),'group')==='support'||S(units.get(id),'regimental')==='no';
const property=(n,key)=>{const own=S(n,key);if(own!==undefined)return own;const a=S(n,'archetype');return a?property(eq.get(a),key):undefined;};
const tech=new Set([...h.definitions(game,'common/technologies','technologies'),...h.definitions(root,'common/technologies','technologies')].map(n=>n.key));
// Category names must come from declared tags, rather than inferred equipment ID prefixes.
const technologyCategories=new Set();
for(const base of [game,root])for(const file of h.files(path.join(base,'common/technology_tags')).filter(f=>f.endsWith('.txt')))
  for(const n of h.parse(fs.readFileSync(file,'utf8')).filter(n=>n.key==='technology_categories'))for(const c of n.value)technologyCategories.add(c.value);
for(const t of h.definitions(root,'common/technologies','technologies'))for(const c of C(t,'categories').flatMap(n=>n.value))if(!technologyCategories.has(c.value))errors.push('Undefined technology category '+t.key+' -> '+c.value);
for(const a of manifest.armor?.aliases||[])if(localEq.some(n=>n.key===a.id))errors.push('Explicit armor collides with native generated role '+a.id);
for(const a of manifest.aircraft?.aliases||[])if(localEq.some(n=>n.key===a.id))errors.push('Explicit aircraft collides with native generated role '+a.id);
const resolve=n=>{const a=S(n,'archetype');const out=a?resolve(eq.get(a)):{};for(const c of n.value){if(c.key==='resources'&&Array.isArray(c.value)){for(const k of Object.keys(out).filter(k=>k.startsWith('resources.')))delete out[k];for(const r of c.value)out['resources.'+r.key]=Number(r.value);}else if(c.key&&typeof c.value==='string'&&/^-?(?:\d+(?:\.\d*)?|\.\d+)$/.test(c.value))out[c.key]=Number(c.value);}return out;};
for(const r of [...values.regular,...values.special]) {
  if(manifest.armor?.replacements[r.id]||manifest.aircraft?.replacements[r.id])continue;
  const n=eq.get(r.id);if(!n){errors.push('Removed model '+r.id);continue;}
  const effective=resolve(n);
  for(const p of r.values.filter(p=>p.custom)){numericChecks++;if(effective[p.key]!==p.custom.value)errors.push(r.id+' '+p.key+': '+p.custom.value+' -> '+effective[p.key]);}
  const metadata=new Set(['year','priority','visual_level','air_map_icon_frame','interface_overview_category_index','land_air_wing_size','carrier_air_wing_size']);
  for(const [key,value] of Object.entries(effective))if(value!==0&&!metadata.has(key)&&!r.values.some(p=>p.key===key&&p.custom))warnings.push(r.id+' additionally inherits '+key+' = '+value);
}
for(const m of manifest.models){const n=eq.get(m.id);if(!n){errors.push('Missing model '+m.id);continue;}
  const a=S(n,'archetype');if(!eq.has(a))errors.push('Unknown archetype '+m.id+' -> '+a);
  if(retired.has(a))errors.push('Retired archetype '+a);
  if(S(n,'is_archetype')==='yes')errors.push('Custom archetype retained '+m.id);
  if(!C(n,'can_be_produced').length)errors.push('Missing country/research production gate '+m.id);
  if(S(n,'active')!==(m.modularHull||m.armorChassis||m.airframe?'yes':'no'))errors.push('Wrong national model/chassis initialization '+m.id);
  if(!m.armorChassis&&!m.airframe&&!C(n,'can_be_produced')[0].value.some(c=>c.key==='has_country_flag'&&c.value==='touhou_registered_model_'+m.id))errors.push('Missing national production registration gate '+m.id);
  if(S(n,'carrier_capable')!==undefined&&S(n,'carrier_capable')!==(property(eq.get(a),'carrier_capable')||'no'))errors.push('Illegal carrier_capable override '+m.id);
}
for(const folder of ['common','events','history/countries','history/units','interface','recp'])for(const f of h.files(path.join(root,folder)).filter(f=>/\.(txt|gui|gfx)$/.test(f))){
  const rel=path.relative(root,f).replaceAll('\\','/');let nodes;
  try{nodes=h.parse(fs.readFileSync(f,'utf8'));checkedFiles++;}catch(e){errors.push(rel+': '+e.message);continue;}
  if(rel.startsWith('history/countries/')&&nodes.some(n=>['else','else_if'].includes(n.key)))errors.push(rel+': unsupported sibling else in country history');
  function walk(ns,parent='') {for(const n of ns){
    for(const token of [n.key,typeof n.value==='string'&&!['picture','sprite','gfx','icon','abbreviation'].includes(n.key)?n.value.replace(/^"|"$/g,''):null])if(token&&retired.has(token))errors.push(rel+': retired identifier '+token);
    if(n.key&&Object.keys(manifest.units).some(id=>n.key.includes('army_sub_unit_'+id+'_')))errors.push(rel+': retired unit modifier '+n.key);
    if(n.key==='has_tech'&&!tech.has(n.value))errors.push(rel+': unresolved has_tech '+n.value);
    if(n.key==='set_technology')for(const c of n.value)if(c.key&&c.key!=='popup'&&!tech.has(c.key))errors.push(rel+': unresolved set_technology '+c.key);
    if(n.key==='enable_equipments')for(const c of n.value)if(!eq.has(c.value))errors.push(rel+': unresolved equipment unlock '+c.value);
    if(n.key==='create_equipment_variant'&&!eq.has(S(n,'type')))errors.push(rel+': unresolved design type '+S(n,'type'));
    if(n.key==='enable_subunits')for(const c of n.value)if(typeof c.value==='string'&&!units.has(c.value))errors.push(rel+': unresolved unit unlock '+c.value);
    if(['regiments','support'].includes(parent)&&n.key&&!units.has(n.key))errors.push(rel+': unresolved template unit '+n.key);
    if(parent==='regiments'&&units.has(n.key)&&nativeSupport(n.key))errors.push(rel+': support-only unit in regiments '+n.key);
    if(parent==='support'&&units.has(n.key)&&!nativeSupport(n.key))errors.push(rel+': line unit in support '+n.key);
    if(n.key==='add_unit_bonus')for(const unit of n.value)if(C(unit,'name').length)errors.push(rel+': engine rejects name inside add_unit_bonus');
    if(Array.isArray(n.value))walk(n.value,n.key||parent);
  }}walk(nodes);
}
// Native technology equipment/module unlock lists must exactly match the installed game.
const vanillaTechnology=new Map(h.definitions(game,'common/technologies','technologies').map(n=>[n.key,n]));
let nativeUnlockListsChecked=0;
for(const t of h.definitions(root,'common/technologies','technologies'))if(vanillaTechnology.has(t.key))for(const key of ['enable_equipments','enable_equipment_modules']){
  const actual=C(t,key).flatMap(n=>n.value).map(n=>n.value),expected=C(vanillaTechnology.get(t.key),key).flatMap(n=>n.value).map(n=>n.value);
  nativeUnlockListsChecked++;if(JSON.stringify(actual)!==JSON.stringify(expected))errors.push('Modified native '+key+' list '+t.key);
}
const militaryEffects=h.parse(fs.readFileSync(path.join(root,'common/scripted_effects/touhou_vanilla_military.txt'),'utf8'));
const registration=militaryEffects.find(n=>n.key==='touhou_register_country_equipment');
const registeredDesigns=C(C(registration,'if')[0],'if');
if(registeredDesigns.length!==manifest.models.filter(m=>!m.armorChassis&&!m.airframe).length)errors.push('Incomplete country model registration');
for(const m of manifest.models.filter(m=>!m.armorChassis&&!m.airframe)){
  const entries=registeredDesigns.filter(n=>S(n,'set_country_flag')==='touhou_registered_model_'+m.id);
  if(entries.length!==1){errors.push('Missing or duplicate country registration '+m.id);continue;}
  const entry=entries[0],design=C(entry,'create_equipment_variant')[0],limit=C(entry,'limit')[0],flag='touhou_registered_model_'+m.id;
  const production=C(eq.get(m.id),'can_be_produced')[0].value.filter(n=>n.key!=='has_country_flag'||n.value!==flag);
  if(h.render(limit.value.slice(0,-1))!==h.render(production))errors.push('Registration/production conditions differ '+m.id);
  if(m.modularHull){if(design)errors.push('Empty modular hull incorrectly registered as a finished design '+m.id);}
  else {
    if(S(design,'type')!==m.id||S(design,'allow_without_tech')!=='yes')errors.push('National design waits for a removed unlock '+m.id);
    if(S(design,'parent_version')!=='0'||C(design,'upgrades').length||C(design,'modules').length)errors.push('National registration changes finished model '+m.id);
  }
  if(!C(limit,'NOT').some(n=>S(n,'has_country_flag')===flag)||S(entry,'set_country_flag')!==flag)errors.push('Missing repeat-registration guard '+m.id);
}
if(h.definitions(root,'common/units','sub_units').length)errors.push('Custom subunit definitions remain');
for(const f of manifest.deleted)if(fs.existsSync(path.join(root,f)))errors.push('Deleted override remains '+f);
for(const b of manifest.bonuses){for(const u of b.bonus)if(!units.has(u.unit))errors.push('Bonus for unknown unit '+u.unit);}
// Newly shared battalions must consume the retained equipment through the same vanilla archetype.
for(const [old,id] of Object.entries(manifest.units)){
  const source=Object.values(baseline.sources).flatMap(s=>h.parse(s).filter(n=>n.key==='sub_units').flatMap(n=>n.value)).find(n=>n.key===old);
  if(!source)continue;
  for(const need of C(source,'need').flatMap(n=>n.value)){
    const target=manifest.archetypes[need.key]||manifest.models.find(m=>m.id===need.key)?.archetype||(eq.has(need.key)?need.key:null);
    if(!target)continue;
    const nativeNeeds=C(units.get(id),'need').flatMap(n=>n.value).map(n=>n.key);
    const roleChange=manifest.equipmentRoleChanges?.[old];
    if(roleChange&&roleChange.unit!==id)errors.push('Stale intentional role change '+old);
    if(!nativeNeeds.includes(target)&&!roleChange&&!['evil_armor_brigade','evil_artillery_brigade'].includes(old))errors.push(old+' -> '+id+' cannot use '+target+'; expects '+nativeNeeds.join(','));
  }
}
const locKeys=new Map();
const locValues=new Map();
for(const file of h.files(path.join(root,'localisation/simp_chinese')).filter(f=>f.endsWith('.yml')))for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){
  const m=line.match(/^\s*([^\s:#]+):\s*\d*\s*"/);if(!m)continue;
  if(locKeys.has(m[1]))errors.push('Duplicate localization '+m[1]+' in '+path.relative(root,file));else locKeys.set(m[1],file);
  const value=line.match(/^\s*[^\s:#]+:\s*\d*\s*"(.*)"\s*$/);if(value)locValues.set(m[1],value[1]);
}
// Native equipment is a prototype for custom models; its own definitions and display stay native.
const nativeOverrides={definitions:[],localisation:[],icons:[]};
for(const n of localEq)if(nativeEquipmentIds.has(n.key))nativeOverrides.definitions.push(n.key);
function identifiesNativeEquipment(key,graphics=false){
  let id=key;
  if(graphics)id=id.replace(/^GFX_/,'').replace(/_(medium|small|large)$/,'');
  else id=id.replace(/_(short|desc)$/,'');
  if(nativeEquipmentIds.has(id))return true;
  id=id.replace(/^[A-Z0-9]{3}_/,'');
  if(graphics)id=id.replace(/^archetype_/,'');
  return nativeEquipmentIds.has(id);
}
for(const key of locKeys.keys())if(identifiesNativeEquipment(key))nativeOverrides.localisation.push(key);
for(const file of h.files(path.join(root,'interface')).filter(f=>f.endsWith('.gfx')))
  for(const top of h.parse(fs.readFileSync(file,'utf8')))if(top.key?.toLowerCase()==='spritetypes')
    for(const n of top.value){const name=S(n,'name')?.replace(/^"|"$/g,'');if(name&&identifiesNativeEquipment(name,true))nativeOverrides.icons.push(name);}
for(const [kind,ids] of Object.entries(nativeOverrides))for(const id of ids)errors.push('Native equipment '+kind+' override '+id);
// Retired research IDs still own the original text, but native IDs need explicit display aliases.
const presentation=manifest.presentation;
if(!presentation)errors.push('Missing native research display mappings');
else {
  const displaySprites=new Map(h.parse(fs.readFileSync(path.join(root,'interface/zz_touhou_military_presentation.gfx'),'utf8'))[0].value.map(n=>[S(n,'name')?.replace(/^"|"$/g,''),n]));
  function checkAlias(key,seen=new Set()) {
    if(!locKeys.has(key)){errors.push('Missing Chinese display text '+key);return;}
    if(seen.has(key)){errors.push('Circular Chinese display alias '+key);return;}
    const next=new Set([...seen,key]);for(const match of (locValues.get(key)||'').matchAll(/\$([^$]+)\$/g))if(locKeys.has(match[1]))checkAlias(match[1],next);
  }
  for(const r of presentation.research) {
    checkAlias(r.tag+'_'+r.id);
    if(r.descriptionSource)checkAlias(r.tag+'_'+r.id+'_desc');
    if(!displaySprites.has('GFX_'+r.tag+'_'+r.id+'_medium'))errors.push('Missing original technology icon '+r.tag+' '+r.id);
  }
  for(const m of manifest.models){checkAlias(m.id);if(!displaySprites.has('GFX_'+m.id+'_medium'))errors.push('Missing retained model icon '+m.id);}
  for(const display of presentation.equipment){
    if(display.presetDesign)continue;
    const model=eq.get(display.id);
    const generic=manifest.models.find(m=>m.id===display.id);
    for(const key of ['picture','variant_name','derived_variant_name'])if(S(model,key)!==display.id+((generic?.armorChassis||generic?.airframe)&&key!=='picture'?'_design':''))errors.push('Model display inherits native identity '+display.id+' '+key);
    const sprite=displaySprites.get('GFX_'+S(model,'picture')+'_medium');
    if(S(sprite,'texturefile')?.replace(/^"|"$/g,'')!==display.texture)errors.push('Model picture resolves to wrong texture '+display.id);
    for(const tag of ['ALI','DES','HAK','DLD','HEL','SSS','OPP','RAB','TEM','BLQ','KAP','TEN','HUM','VAM','MLS','EVI']){
      for(const suffix of ['','_short'])checkAlias(tag+'_'+display.id+suffix);
      if(locValues.get(tag+'_'+display.id)!=='$'+display.nameSource+'$')errors.push('Country uses wrong equipment name '+tag+' '+display.id);
      if(locValues.get(tag+'_'+display.id+'_short')!=='$'+display.shortNameSource+'$')errors.push('Country uses wrong abbreviated equipment name '+tag+' '+display.id);
    }
    const entry=registeredDesigns.find(n=>S(n,'set_country_flag')==='touhou_registered_model_'+display.id),design=entry?C(entry,'create_equipment_variant')[0]:null;
    if(design&&JSON.parse(S(design,'name'))!==locValues.get(display.id))errors.push('Registered design name differs from original equipment name '+display.id);
    if(design&&JSON.parse(S(design,'icon'))!=='GFX_'+display.id+'_medium')errors.push('Registered design uses wrong icon '+display.id);
  }
  const localTechnologies=new Map(h.definitions(root,'common/technologies','technologies').map(n=>[n.key,n]));
  for(const [key,info] of Object.entries(presentation.equipmentTooltips||{})){
    checkAlias(key);
    for(const id of info.models)if(!locValues.get(key)?.includes('$'+id+'$'))errors.push('Research tooltip omits concrete equipment name '+id);
    const effect=C(localTechnologies.get(info.technology),'on_research_complete')[0];
    if(!h.render([effect]).includes('custom_effect_tooltip = '+key))errors.push('Unconnected research model tooltip '+key);
  }
  if(presentation.nativeEquipment.length)errors.push('Presentation must not customize native equipment');
  for(const r of presentation.sprites)if(!fs.existsSync(path.join(root,r.texture))&&!fs.existsSync(path.join(game,r.texture)))errors.push('Missing display texture '+r.name+' '+r.texture);
}
// Global on_actions start without a country; country effects must be entered through a country iterator.
const repairActions=h.parse(fs.readFileSync(path.join(root,'common/on_actions/touhou_runtime_repairs.txt'),'utf8'));
function checkRepairScope(ns,country=false){for(const n of ns){if(n.key==='touhou_check_runtime_repairs'&&!country)errors.push('Runtime repair called without country scope');if(Array.isArray(n.value))checkRepairScope(n.value,country||['every_country','random_country'].includes(n.key));}}
checkRepairScope(repairActions);
const weather=fs.readFileSync(path.join(root,'map/weatherpositions.txt'),'utf8').trimEnd().split(/\r?\n/);
for(let i=0;i<weather.length;i++)if(weather[i].split(';').length!==5)errors.push('weatherpositions.txt invalid argument count at '+(i+1));
const armorResult=require('./armor_validation.cjs').validateArmor({root,game,manifest,eq,values,errors});
numericChecks+=armorResult.numericChecks;
if(armorResult.blueprintValues)fs.writeFileSync(path.join(root,'docs/装甲预设装配数值.json'),JSON.stringify(armorResult.blueprintValues,null,2)+'\n');
delete armorResult.blueprintValues;
const aircraftResult=require('./aircraft_validation.cjs').validateAircraft({root,game,manifest,eq,values,errors});
numericChecks+=aircraftResult.numericChecks;
if(aircraftResult.blueprintValues)fs.writeFileSync(path.join(root,'docs/飞机预设装配数值.json'),JSON.stringify(aircraftResult.blueprintValues,null,2)+'\n');
delete aircraftResult.blueprintValues;
const result={checkedFiles,retainedOriginalModels:values.regular.length+values.special.length,totalModels:localEq.length,numericChecks,armor:armorResult,aircraft:aircraftResult,countryUnlocks:{nativeUnlockListsChecked,registeredModels:registeredDesigns.length,finishedDesigns:manifest.models.filter(m=>!m.modularHull&&!m.armorChassis&&!m.airframe).length,projectGatedModularHulls:manifest.models.filter(m=>m.modularHull).length},nativeEquipmentProtection:{definitionOverrides:nativeOverrides.definitions.length,localisationOverrides:nativeOverrides.localisation.length,iconOverrides:nativeOverrides.icons.length},presentation: presentation?{countryTechnologyMappings:presentation.research.length,retainedModelIcons:presentation.equipment.length,spriteAliases:presentation.sprites.length,countryEquipmentNames:presentation.equipment.length*16,researchModelTooltips:Object.keys(presentation.equipmentTooltips||{}).length}:null,errors:[...new Set(errors)],warnings};
fs.writeFileSync(path.join(root,'docs/幻想乡军事原版化校验.json'),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result,null,2));if(result.errors.length)process.exitCode=1;
